apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: coeur-sync
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: coeur-sync
            image: eu.gcr.io/professionalserviceslabs/coeur-sync:2.0.1:latest
            args: #TODO CHANGE THE FOLLOWING ARGS
            - bin/product-publish-state-import
            - --projectKey
            - carharrt-demo-83
            - --logLevel
            - info
            env:
            - name: COEUR_SOURCE_PROJECT_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: source_project_key
            - name: COEUR_SOURCE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: source_client_id
            - name: COEUR_SOURCE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: source_client_secret
            - name: COEUR_TARGET_PROJECT_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: target_project_key
            - name: COEUR_TARGET_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: target_client_id
            - name: COEUR_TARGET_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: target_client_secret
          restartPolicy: Never
