apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ template "fullname" . }}
            release: "{{ .Release.Name }}"
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          containers:
            - name: {{ .Values.image.name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
              - java
              - -Xmx400m
              - -jar
              - /home/coeur-sync.jar
              - -s
              - products
              env:
              - name: COEUR_SOURCE_PROJECT_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ template "fullname" . }}
                    key: source_ctp_project_key

              - name: COEUR_SOURCE_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ template "fullname" . }}
                    key: source_ctp_client_id

              - name: COEUR_SOURCE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ template "fullname" . }}
                    key: source_ctp_client_secret

              - name: COEUR_TARGET_PROJECT_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ template "fullname" . }}
                    key: target_ctp_project_key

              - name: COEUR_TARGET_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ template "fullname" . }}
                    key: target_ctp_client_id

              - name: COEUR_TARGET_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ template "fullname" . }}
                    key: target_ctp_client_secret

              securityContext:
                capabilities:
                  drop:
                  - SETPCAP
                  - MKNOD
                  - AUDIT_WRITE
                  - CHOWN
                  - NET_RAW
                  - DAC_OVERRIDE
                  - FOWNER
                  - FSETID
                  - KILL
                  - SETGID
                  - SETUID
                  - NET_BIND_SERVICE
                  - SYS_CHROOT
                  - SETFCAP
                readOnlyRootFilesystem: true
              resources:
                {{ toYaml .Values.resources }}
