apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ .Values.image.name }}
type: Opaque
data:
  source_ctp_project_key: {{ .Values.sourceCtpProjectKey }}
  source_ctp_client_id: {{ .Values.sourceCtpClientId | b64enc }}
  source_ctp_client_secret: {{ .Values.sourceCtpClientSecret | b64enc }}
  source_ctp_project_key: {{ .Values.targetCtpProjectKey }}
  target_ctp_client_id: {{ .Values.targetCtpClientId | b64enc }}
  target_ctp_client_secret: {{ .Values.targetCtpClientSecret | b64enc }}
